name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for submitting your issue. We will review it soon.'
        pr-message: 'Thanking for making a pull request. Your request will be reviewed by the maintainers and feedback will come soon!'
